### ISSUE TITLE
This is cool, but what's the point?

### ISSUE THREAD

**Issue by banister** [mullvad/pfctl-rs#68]
Why not just `exec` and hit the `pfctl` executable? I'm curious about this project, but i don't understand the use-case!

Hope you can explain?

**Comment by pronebird** [comment]
Hi @banister,

There are many benefits of using programmatic interfaces vs. command line tools in the context of building applications. Please ask on StackOverflow as it's a more suitable place for general programming questions.

Cheers,
Andrej
