### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Ch00k** [mullvad/pfctl-rs#77]
I am building https://github.com/mullvad/mullvadvpn-app/ on Apple M1, and for that I need pfctl-rs with https://github.com/mullvad/pfctl-rs/pull/75 fix. Is there anything that could prevent releasing a new version of the crate with https://github.com/mullvad/pfctl-rs/pull/75 included? I'd love to have one 🙏 😃

**Comment by faern** [comment]
Done! Published as `0.4.1`.
