### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jeff-hiner** [mullvad/pfctl-rs#82]
Any chance we can get a new release containing https://github.com/mullvad/pfctl-rs/pull/81?

**Comment by jeff-hiner** [comment]
Bump? I'd like to see these changes in the crates.io release, if possible.

**Comment by pronebird** [comment]
Ping @faern

**Comment by faern** [comment]
Done! https://github.com/mullvad/pfctl-rs/releases/tag/0.4.5 https://crates.io/crates/pfctl/0.4.5
